---
driver:
  name: vagrant
  privileged: true
  use_sudo: false
provisioner:
  name: chef_solo
  require_chef_omnibus: 12.21.14

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec
#   format: doc

platforms:
  - name: centos-7.2
    driver_config:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[hello_chef::default]
    attributes:
