name 'hello_chef'
maintainer 'Basil Paul'
maintainer_email 'paul.basil@gmail.com'
license 'all_rights'
description 'Installs/Configures hello_chef'
long_description 'Installs/Configures hello_chef'
version '0.1.0'

depends 'python'
depends 'openssl'
depends 'nginx'